apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: ars-character-creator
resources:
  - npc_creator_deployment.yaml
configMapGenerator:
  - name: ars-character-creator-map
    literals:
      - KEY=value
